### ISSUE TITLE
What does the library do on versions under Android 5.0?

### ISSUE THREAD

**Issue by escobar5** [kumparan/react-native-android-inapp-update#10]
Hi,

Does the library throws an error when using it on Android < 5, or does it do nothing?

I need to know how to handle that case in my app.

Thanks

**Comment by gedeagas** [comment]
@escobar5 Hi, our library is designed to run on react-native which is only run on Android 5.0 (API 21) or newer. If you are using react-native then you are only able to support Android version 5.0 >=.

**Comment by escobar5** [comment]
I didn't remember the min android api supported. thanks

**Comment by CyxouD** [comment]
@gedeagas version of RN before 64 supports < 5.0 API
