### ISSUE TITLE
  error

### ISSUE THREAD

**Issue by jinalcodemonk48** [kumparan/react-native-android-inapp-update#11]
error: [Error: checkAppUpdate failure: com.google.android.play.core.internal.ar: Failed to bind to the service.]

**Comment by gedeagas** [comment]
Hi @jinalcodemonk48 are you running the app on real device?

**Comment by jinalcodemonk48** [comment]
i try with both emulator and real device

**Comment by jinalcodemonk48** [comment]
i need to any file  update in android folder ?

**Comment by gedeagas** [comment]
@jinalcodemonk48 this error is ussualy occured because the device you are using does not have Google Play Services. 

Do you have any example repo that we can use to test the problem?

**Comment by gedeagas** [comment]
Closed due to inactivity
