### ISSUE TITLE
No Update available for "startUpdateFlow" method, but available for "checkUpdateAvailability" method.

### ISSUE THREAD

**Issue by HorbachAndrii** [kumparan/react-native-android-inapp-update#13]
Thanks for the library.

When I try to update my app the startUpdateFlow method doesn't see any updates.
It's happening because we have two validation that blocks the update.
1. https://github.com/kumparan/react-native-android-inapp-updates/blob/c9c719473fb6198cc1e90e45771eaef9356f259b/android/src/main/java/com/agastya/androidinappupdates/AndroidInappUpdatesModule.java#L66
2. https://github.com/kumparan/react-native-android-inapp-updates/blob/c9c719473fb6198cc1e90e45771eaef9356f259b/android/src/main/java/com/agastya/androidinappupdates/AndroidInappUpdatesModule.java#L67
Method `appUpdateInfo.clientVersionStalenessDays()`, always return null.
If I remove these two lines then I can update my app.

I'm testing my app using [Internal App Sharing](https://play.google.com/console/internal-app-sharing).
Also, I have enabled "Internal access to applications" in the Play Store application. 

My code.
```
try {
  const checkUpdateAvailabilityResult = await checkUpdateAvailability();
  if (checkUpdateAvailabilityResult === `Update available`) {
    Alert.alert(`${versionCode} checkUpdateAvailability result:`, JSON.stringify(checkUpdateAvailabilityResult));
    try {
      const startUpdateFlowResult = await startUpdateFlow(`immediate`, 0);
      Alert.alert(`${versionCode} startUpdateFlowResult: `, JSON.stringify(startUpdateFlowResult));
    } catch (error) {
      Alert.alert(`${versionCode} startUpdateFlowResult error: `, JSON.stringify(error));
    }
  }
} catch (error) {
    Alert.alert(`${versionCode} checkUpdateAvailability error:`, JSON.stringify(error));
}
```

Any ideas?

**Comment by gedeagas** [comment]
hi @HorbachAndrii would you help us by making a PR ?

**Comment by HorbachAndrii** [comment]
> hi @HorbachAndrii would you help us by making a PR ?

On the weekend I will try to make a PR

**Comment by HorbachAndrii** [comment]
@gedeagas Made [PR](https://github.com/kumparan/react-native-android-inapp-updates/pull/15)

**Comment by gedeagas** [comment]
Thank you for the pr @HorbachAndrii
