### ISSUE TITLE
Adding support for `Flow` type and update `TypeScript` definition.

### ISSUE THREAD

**Issue by gedeagas** [kumparan/react-native-android-inapp-update#3]
Currently, we only have typing for `TypeScript` but are not up to date and we are planning to add `Flow` type.

**Comment by gedeagas** [comment]
cc @ybbond

**Comment by ShivamJoker** [comment]
Any updates on this ?

**Comment by gedeagas** [comment]
@ShivamJoker the typing for Flow and TypeScript now are available. Thank you @imdbsd
