### ISSUE TITLE
Updating flow doesn't work

### ISSUE THREAD

**Issue by ravindranpandu** [kumparan/react-native-android-inapp-update#5]
Hello, 

Thank you for providing us the native android in app update feature to react-native, really appreciate your work, I followed the documentation and i integrated the module to my app and i could see the flexible update dialog pops up as soon as i open the app, but when i tap on update button the dialog closes and nothing happens.

I debugged in console to check the promise and it returned `Successful`, but i didn't see the installing progress screen or neither did the update happened, i restarted the app after giving it 5 to 10 minutes and the build number is still same as the previous one which means it's not updated and in the console the promised returned `No update available`. When i uninstalled the app and installed the same version again, i could see the update dialog again when i tap on the install button the same thing happens, it just doesn't do anything after the dialog dismiss.

I am just calling my update method in `componentDidMount` of the `App.js`.

```
// App.js
componentDidMount() {
     this.checkForUpdate();
}

checkForUpdate = async () => {
     const checkUpdateResult = await checkUpdateAvailability();        

     if (checkUpdateResult === 'Update available') {
          const updateFlowResult = await startUpdateFlow('flexible');                   
     } 
}
```

Please let me know if i am missing something here?

**Comment by renopp** [comment]
Hi @ravindranpandu 
Have you implement `onCompleteUpdate()` function?

**Comment by gedeagas** [comment]
Hi  @ravindranpandu thank you for making an issue. Sadly this step is not well documented on our repo and thanks for your report we will update the docs. 

Currently, to apply the update you will need to trigger the `onCompleteUpdate()` function. 
Usually, we apply this after listening to `installStatus`. If the event status returns 11 it means that the download have been finished and ready to restart. 

```
import {NativeEventEmitter, NativeModules} from 'react-native';
import {onCompleteUpdate} from '@gurukumparan/react-native-android-inapp-updates';

 const eventEmitter = new NativeEventEmitter(
        NativeModules.AndroidInappUpdates
 );

const installStatus = eventEmitter.addListener(
        'installStatus',
        (event: number) => {
          //11 is downloaded status
          if (event === 11) {
            onCompleteUpdate();
          }
        }
      );
```

**Comment by ravindranpandu** [comment]
@gedeagas @renopp thanks for the swift response, i realised that the `onCompleteUpdate` function was missing in the document, later i found [this](https://www.naroju.com/implementing-android-in-app-updates-in-react-native/) post and figured it out i did the same step which is pointed out in @gedeagas response and now i could see the installation process. Many thanks guys 👍

**Comment by gedeagas** [comment]
Awesome, glad to help @ravindranpandu.

**Comment by CyxouD** [comment]
@gedeagas Could you say why was it closed? I've experienced the same issue as @ravindranpandu. Was it fixed without event emitter which still is not in docs?
